# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from main_app.grpc import useraccount_pb2 as main__app_dot_grpc_dot_useraccount__pb2


class UserAccountStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/useraccount.UserAccount/GetUser',
                request_serializer=main__app_dot_grpc_dot_useraccount__pb2.UserId.SerializeToString,
                response_deserializer=main__app_dot_grpc_dot_useraccount__pb2.User.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/useraccount.UserAccount/CreateUser',
                request_serializer=main__app_dot_grpc_dot_useraccount__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=main__app_dot_grpc_dot_useraccount__pb2.User.FromString,
                )
        self.LoginUser = channel.unary_unary(
                '/useraccount.UserAccount/LoginUser',
                request_serializer=main__app_dot_grpc_dot_useraccount__pb2.LoginUserRequest.SerializeToString,
                response_deserializer=main__app_dot_grpc_dot_useraccount__pb2.LoginUserResponse.FromString,
                )


class UserAccountServicer(object):
    """Interface exported by the server.
    """

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=main__app_dot_grpc_dot_useraccount__pb2.UserId.FromString,
                    response_serializer=main__app_dot_grpc_dot_useraccount__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=main__app_dot_grpc_dot_useraccount__pb2.CreateUserRequest.FromString,
                    response_serializer=main__app_dot_grpc_dot_useraccount__pb2.User.SerializeToString,
            ),
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=main__app_dot_grpc_dot_useraccount__pb2.LoginUserRequest.FromString,
                    response_serializer=main__app_dot_grpc_dot_useraccount__pb2.LoginUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'useraccount.UserAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserAccount(object):
    """Interface exported by the server.
    """

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/useraccount.UserAccount/GetUser',
            main__app_dot_grpc_dot_useraccount__pb2.UserId.SerializeToString,
            main__app_dot_grpc_dot_useraccount__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/useraccount.UserAccount/CreateUser',
            main__app_dot_grpc_dot_useraccount__pb2.CreateUserRequest.SerializeToString,
            main__app_dot_grpc_dot_useraccount__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/useraccount.UserAccount/LoginUser',
            main__app_dot_grpc_dot_useraccount__pb2.LoginUserRequest.SerializeToString,
            main__app_dot_grpc_dot_useraccount__pb2.LoginUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
